services:
  app:
    image: ghcr.io/joeyates/imap-backup:latest
    restart: unless-stopped
    command: ["/start.sh"]
    user: 1000:1000
    volumes:
      - app_data:/data
      - $PWD/start.sh:/start.sh
    labels:
      - ofelia.restart=true
      - ofelia.enabled=true
      - "ofelia.job-exec.${COMPOSE_PROJECT_NAME}cron.schedule=0 0 12 * * *"
      - "ofelia.job-exec.${COMPOSE_PROJECT_NAME}cron.user=1000"
      - "ofelia.job-exec.${COMPOSE_PROJECT_NAME}cron.command=/start.sh cron"
    env_file:
      - .env

volumes:
  app_data: